name: Reusable workflow example

on:
  workflow_call:
  
    inputs:
    
      jdk:
        required: true
        type: string

jobs:
  maven-build:
    runs-on: ubuntu-latest
    
    steps:

    - uses: actions/checkout@v4
    
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: ${{ inputs.jdk }}
        distribution: 'temurin'
        cache: maven
        
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    
    
