name: Use Composite Action

on:
  workflow_dispatch:
    

jobs:
  use-composite-action:
    runs-on: ubuntu-latest

    steps:
    
    - name: Build
      uses: ./.github/actions/build
      with:
        jdk: 17
